---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: presync-wait-repo-secret-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ coalesce $.Values.mgmt.gitops.hook_image $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: wait-repo-secret-job
          env:
            - name: SLEEP
              value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for repository cred's"
              while :
              do
                sleep $SLEEP
                if `oc get secret -n {{ $.Values.global.gitops.namespace }} | egrep repo-{{ $.Values.cluster.name }}.{{ $.Values.global.domain }}`
                then break
                fi
              done
              echo "All done! Hooray!"
              sleep $SLEEP
