---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  #annotations:
  #  argocd.argoproj.io/sync-wave: "1"
  name: {{ $.Values.cluster.name }}
  namespace: {{ $.Values.cluster.name }}
spec:
  #agentLabelSelector:
  #  matchLabels:
  #    telco-core: core-{{ $.Values.cluster.name }}
  additionalNTPSources:
    - {{ $.Values.global.ntp }}
  clusterRef:
    name: {{ $.Values.cluster.name }}
    namespace: {{ $.Values.cluster.name }}
  ## (optional pub key)
  sshAuthorizedKey: '{{ coalesce $.Values.cluster.ssh_key $.Values.global.ai.ssh_key }}'
  pullSecretRef:
    name: {{ $.Values.global.ai.pull_secret_name }}
    #name: assisted-deployment-pull-secret
  # proxy:
  #   httpProxy: http://11.11.11.33
  #   httpsProxy: http://22.22.22.55
  # Modify ignition during discovery
  #ignitionConfigOverride: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/etc/someconfig", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}'
  ## Custom network configuration
  nmStateConfigLabelSelector:
    matchLabels:
      nmstate-label: {{ $.Values.cluster.name }}
