---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    workload.openshift.io/allowed: management
  creationTimestamp: "2022-05-21T14:05:53Z"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-ptp
spec: {}