---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ptp-operator-subscription
  namespace: openshift-ptp
spec:
  channel: stable
  installPlanApproval: Automatic
  name: ptp-operator
  #source: redhat-operators
  source: redhat-operator-index
  sourceNamespace: openshift-marketplace